### ISSUE TITLE
Request for testing Heltec Wireless Stick configuration

### ISSUE THREAD

**Issue by matthias-bs** [matthias-bs/BresserWeatherSensorTTN#49]
Please test the [Heltec Wireless Stick](https://heltec.org/project/wireless-stick/) configuration and provide your feedback!

Deep-sleep current consumption would be interesting, too!

**Comment by matthias-bs** [comment]
@jorgenavarroortiz It would be great if you could spend a little time on this!

**Comment by matthias-bs** [comment]
Please refer to https://github.com/matthias-bs/BresserWeatherSensorTTN#software-build-setup and select the following board:
![grafik](https://user-images.githubusercontent.com/83612361/222923377-6493ce2c-adcc-48e5-ae3f-f9f4e80c7821.png)

**Comment by jorgenavarroortiz** [comment]
Sure! Just give me a few days and I will try to connect this board to TTN :-)

**Comment by jorgenavarroortiz** [comment]
Hi! The pinout is ok since I am receiving data on TTN. However, I think I have some problem with the decoder (ttn_decoder_fp.js) since the data do not show proper values. If you have some simple steps that I can follow to test this, it would be great. On BresserWeatherSensorTTNCfg.h I have only enabled SENSORID_EN and RAINDATA_EN, and I have updated the javascript formatter on TTN. However, results are strange... I will try to make it work in the next days.

**Comment by matthias-bs** [comment]
Hi,
Thank you very much for testing!

In https://github.com/matthias-bs/BresserWeatherSensorTTN/blob/main/decoder_basic.js there is a more detailed explanation how to set the decoder based on the Arduino sketch configuration.
Or you could try https://github.com/matthias-bs/BresserWeatherSensorTTN/blob/main/scripts/generate_decoder.py to generate the decoder's core function automatically from your BresserWeatherSensorTTNCfg.h.
